def translate(sentence):
    sentence = sentence.lower()
    sentence = sentence.replace("e", "a")
    sentence = sentence.replace("i", "e")
    sentence = sentence.replace("u", "e")
    sentence = sentence.replace("o", "u")
    sentence = sentence.replace("y", "o")
    sentence = sentence.replace("c", "kk")
    sentence = sentence.replace("j", "y")
    sentence = sentence.replace("q", "gg")
    sentence = sentence.replace("w", "vv")
    sentence = sentence.replace("x", "hh")
    sentence = sentence.replace("z", "ss")
    sentence = sentence.replace("bl", "mm")
    sentence = sentence.replace("br", "nn")
    sentence = sentence.replace("dh", "gg")
    sentence = sentence.replace("dr", "kr")
    sentence = sentence.replace("es", "nn")
    sentence = sentence.replace("fl", "vv")
    sentence = sentence.replace("fr", "ff")
    sentence = sentence.replace("gh", "kn")
    sentence = sentence.replace("gl", "bl")
    sentence = sentence.replace("gr", "br")
    sentence = sentence.replace("nd", "sk")
    sentence = sentence.replace("ng", "nk")
    sentence = sentence.replace("ph", "ff")
    sentence = sentence.replace("pl", "gl")
    sentence = sentence.replace("pr", "fr")
    sentence = sentence.replace("sk", "kk")
    sentence = sentence.replace("sl", "ll")
    sentence = sentence.replace("sm", "mm")
    sentence = sentence.replace("sn", "nn")
    sentence = sentence.replace("sp", "pp")
    sentence = sentence.replace("st", "tt")
    sentence = sentence.replace("th", "ss")
    sentence = sentence.replace("tr", "dr")
    # Replace some vowel clusters
    sentence = sentence.replace("ay", "aa")
    sentence = sentence.replace("aa", "ä")
    sentence = sentence.replace("ae", "ã")
    sentence = sentence.replace("ea", "õ")
    sentence = sentence.replace("ei", "ë")
    sentence = sentence.replace("ie", "yy")
    sentence = sentence.replace("io", "yy")
    sentence = sentence.replace("oe", "ö")
    sentence = sentence.replace("oi", "oo")
    sentence = sentence.replace("ou", "oo")
    sentence = sentence.replace("ue", "ü")
    sentence = sentence.replace("uo", "uu")
    sentence = sentence.replace("uy", "uu")
    sentence = sentence.replace("yu", "yy")
    sentence = sentence.replace("ya", "yy")
    sentence = sentence.replace("yi", "ÿ")
    # Put a vowel before double consonants
    sentence = sentence.replace("bb", "abb")
    sentence = sentence.replace("dd", "edd")
    sentence = sentence.replace("ff", "yff")
    sentence = sentence.replace("gg", "ogg")
    sentence = sentence.replace("hh", "uhh")
    sentence = sentence.replace("kk", "akk")
    sentence = sentence.replace("ll", "ell")
    sentence = sentence.replace("mm", "ymm")
    sentence = sentence.replace("nn", "onn")
    sentence = sentence.replace("pp", "upp")
    sentence = sentence.replace("rr", "arr")
    sentence = sentence.replace("ss", "ess")
    sentence = sentence.replace("tt", "ytt")
    sentence = sentence.replace("vv", "ovv")
    # Remove triple consonants
    sentence = sentence.replace("bbb", "bb")
    sentence = sentence.replace("ddd", "dd")
    sentence = sentence.replace("fff", "ff")
    sentence = sentence.replace("ggg", "gg")
    sentence = sentence.replace("hhh", "hh")
    sentence = sentence.replace("kkk", "kk")
    sentence = sentence.replace("lll", "ll")
    sentence = sentence.replace("mmm", "mm")
    sentence = sentence.replace("nnn", "nn")
    sentence = sentence.replace("ppp", "pp")
    sentence = sentence.replace("rrr", "rr")
    sentence = sentence.replace("sss", "ss")
    sentence = sentence.replace("ttt", "tt")
    sentence = sentence.replace("vvv", "vv")
    # Replace triple vowels
    sentence = sentence.replace("aaa", "aa")
    sentence = sentence.replace("äää", "ää")
    sentence = sentence.replace("ããã", "ãã")
    sentence = sentence.replace("eee", "ee")
    sentence = sentence.replace("ëëë", "ëë")
    sentence = sentence.replace("ooo", "oo")
    sentence = sentence.replace("ööö", "öö")
    sentence = sentence.replace("õõõ", "õõ")
    sentence = sentence.replace("uuu", "uu")
    sentence = sentence.replace("üüü", "üü")
    sentence = sentence.replace("yyy", "yy")
    sentence = sentence.replace("ÿÿÿ", "ÿÿ")
    # Capitalize the first letter
    sentence = sentence.capitalize()
    # Return the sentence
    return sentence


def File():
    with open('C:/FILES/Others/Others/Todo.txt', 'r') as file:
        text = file.read()
        text = translate(text)
        with open('C:/Users/Bence/Downloads/Out.txt', 'w') as file:
            file.write(text)
        file.close()


text = "Test sentence"
result = translate(text)
print(result)
