def cyrillic(sentence):
    sentence = sentence.replace("A", "А")
    sentence = sentence.replace("Ä", "Ӓ")
    sentence = sentence.replace("B", "Б")
    sentence = sentence.replace("D", "Д")
    sentence = sentence.replace("E", "Е")
    sentence = sentence.replace("Ë", "Ё")
    sentence = sentence.replace("G", "Г")
    sentence = sentence.replace("H", "Х")
    sentence = sentence.replace("K", "К")
    sentence = sentence.replace("L", "Л")
    sentence = sentence.replace("M", "М")
    sentence = sentence.replace("N", "Н")
    sentence = sentence.replace("O", "О")
    sentence = sentence.replace("Ö", "Ӧ")
    sentence = sentence.replace("P", "П")
    sentence = sentence.replace("R", "Р")
    sentence = sentence.replace("S", "С")
    sentence = sentence.replace("T", "Т")
    sentence = sentence.replace("U", "У")
    sentence = sentence.replace("Ü", "Ӱ")
    sentence = sentence.replace("V", "В")
    sentence = sentence.replace("Y", "И")
    sentence = sentence.replace("Ÿ", "Ӥ")
    sentence = sentence.replace("a", "а")
    sentence = sentence.replace("ä", "ӓ")
    sentence = sentence.replace("b", "б")
    sentence = sentence.replace("d", "д")
    sentence = sentence.replace("e", "е")
    sentence = sentence.replace("ë", "ё")
    sentence = sentence.replace("g", "г")
    sentence = sentence.replace("h", "х")
    sentence = sentence.replace("k", "к")
    sentence = sentence.replace("l", "л")
    sentence = sentence.replace("m", "м")
    sentence = sentence.replace("n", "н")
    sentence = sentence.replace("o", "о")
    sentence = sentence.replace("ö", "ӧ")
    sentence = sentence.replace("p", "п")
    sentence = sentence.replace("r", "р")
    sentence = sentence.replace("s", "с")
    sentence = sentence.replace("t", "т")
    sentence = sentence.replace("u", "у")
    sentence = sentence.replace("ü", "ӱ")
    sentence = sentence.replace("v", "в")
    sentence = sentence.replace("y", "и")
    sentence = sentence.replace("ÿ", "ӥ")
    return sentence


def translate_text(sentence):
    sentence = sentence.lower()
    sentence = sentence.replace("o", "y")
    sentence = sentence.replace("e", "o")
    sentence = sentence.replace("i", "a")
    sentence = sentence.replace("u", "e")
    sentence = sentence.replace("c", "m")
    sentence = sentence.replace("f", "h")
    sentence = sentence.replace("j", "d")
    sentence = sentence.replace("q", "v")
    sentence = sentence.replace("w", "t")
    sentence = sentence.replace("x", "g")
    sentence = sentence.replace("z", "k")
    # Replace common consonant clusters
    sentence = sentence.replace("bl", "o")
    sentence = sentence.replace("br", "u")
    sentence = sentence.replace("dr", "ü")
    sentence = sentence.replace("gh", "p")
    sentence = sentence.replace("gl", "s")
    sentence = sentence.replace("gr", "ÿ")
    sentence = sentence.replace("gu", "b")
    sentence = sentence.replace("kn", "v")
    sentence = sentence.replace("kr", "ä")
    sentence = sentence.replace("ks", "b")
    sentence = sentence.replace("lm", "v")
    sentence = sentence.replace("ln", "y")
    sentence = sentence.replace("lp", "ä")
    sentence = sentence.replace("mn", "ÿ")
    sentence = sentence.replace("mr", "d")
    sentence = sentence.replace("ms", "e")
    sentence = sentence.replace("nl", "y")
    sentence = sentence.replace("nr", "e")
    sentence = sentence.replace("ph", "ÿ")
    sentence = sentence.replace("pr", "h")
    sentence = sentence.replace("ps", "k")
    sentence = sentence.replace("pt", "l")
    sentence = sentence.replace("rm", "d")
    sentence = sentence.replace("rn", "e")
    sentence = sentence.replace("rs", "l")
    sentence = sentence.replace("rt", "m")
    sentence = sentence.replace("sh", "ä")
    sentence = sentence.replace("sk", "b")
    sentence = sentence.replace("sl", "d")
    sentence = sentence.replace("sm", "e")
    sentence = sentence.replace("sn", "ë")
    sentence = sentence.replace("sp", "k")
    sentence = sentence.replace("st", "n")
    sentence = sentence.replace("th", "b")
    sentence = sentence.replace("tr", "m")
    sentence = sentence.replace("ts", "n")
    # Replace start vowels
    sentence = sentence.replace(" a", " ta")
    sentence = sentence.replace(" ä", " rä")
    sentence = sentence.replace(" e", " ne")
    sentence = sentence.replace(" ë", " lë")
    sentence = sentence.replace(" o", " ho")
    sentence = sentence.replace(" ö", " dö")
    sentence = sentence.replace(" u", " du")
    sentence = sentence.replace(" ü", " hü")
    sentence = sentence.replace(" y", " ly")
    sentence = sentence.replace(" ÿ", " nÿ")
    # Replace end vowels
    sentence = sentence.replace("a ", "av ")
    sentence = sentence.replace("ä ", "ät ")
    sentence = sentence.replace("e ", "es ")
    sentence = sentence.replace("ë ", "ër ")
    sentence = sentence.replace("o ", "op ")
    sentence = sentence.replace("ö ", "ön ")
    sentence = sentence.replace("u ", "um ")
    sentence = sentence.replace("ü ", "ül ")
    sentence = sentence.replace("y ", "yk ")
    sentence = sentence.replace("ÿ ", "ÿh ")
    # Put a vowel before double consonants
    sentence = sentence.replace("bb", "abb")
    sentence = sentence.replace("dd", "edd")
    sentence = sentence.replace("gg", "ogg")
    sentence = sentence.replace("hh", "uhh")
    sentence = sentence.replace("kk", "ykk")
    sentence = sentence.replace("ll", "ull")
    sentence = sentence.replace("mm", "omm")
    sentence = sentence.replace("nn", "enn")
    sentence = sentence.replace("pp", "app")
    sentence = sentence.replace("rr", "err")
    sentence = sentence.replace("ss", "oss")
    sentence = sentence.replace("tt", "utt")
    sentence = sentence.replace("vv", "yvv")
    # Replace few letters
    new_sentence = ""
    for line in sentence.split("\n"):
        new_sentence_line = ""
        for word in line.split():
            if len(word) < 3:
                new_sentence_line += word
            else:
                new_sentence_line += word + " "
        new_sentence += new_sentence_line + "\n"
    sentence = new_sentence
    if sentence[-1] == "\n":
        sentence = sentence[:-1]
    # Eliminate triple letters
    sentence = sentence.replace("aaa", "aa")
    sentence = sentence.replace("äää", "ää")
    sentence = sentence.replace("bbb", "bb")
    sentence = sentence.replace("ddd", "dd")
    sentence = sentence.replace("eee", "ee")
    sentence = sentence.replace("ëëë", "ëë")
    sentence = sentence.replace("ggg", "gg")
    sentence = sentence.replace("hhh", "hh")
    sentence = sentence.replace("kkk", "kk")
    sentence = sentence.replace("lll", "ll")
    sentence = sentence.replace("mmm", "mm")
    sentence = sentence.replace("nnn", "nn")
    sentence = sentence.replace("ooo", "oo")
    sentence = sentence.replace("ööö", "öö")
    sentence = sentence.replace("ppp", "pp")
    sentence = sentence.replace("rrr", "rr")
    sentence = sentence.replace("sss", "ss")
    sentence = sentence.replace("ttt", "tt")
    sentence = sentence.replace("uuu", "uu")
    sentence = sentence.replace("üüü", "üü")
    sentence = sentence.replace("vvv", "vv")
    sentence = sentence.replace("yyy", "yy")
    sentence = sentence.replace("ÿÿÿ", "ÿÿ")
    # Capitalize the first letter
    sentence = sentence.capitalize()
    # Return the sentence
    return sentence


def translate_file(source, output):
    with open(source, 'r', encoding='utf-8') as file:
        text = file.read()
        text = translate_text(text) + "\n" + cyrillic(translate_text(text))
        with open(output, 'w', encoding='utf-8') as file:
            file.write(text)
        file.close()


translate_file("C:/Users/Bence/Downloads/Input.txt",
               "C:/Users/Bence/Downloads/Output.txt")

text = "File translation to Liinglish as both latin and cyrillic writing systems were successfully completed!"
result = translate_text(text)
print(result)
print(cyrillic(result))
