def translate_text(sentence):
    sentence = sentence.lower()
    sentence = sentence.replace("e", "a")
    sentence = sentence.replace("i", "e")
    sentence = sentence.replace("u", "e")
    sentence = sentence.replace("o", "u")
    sentence = sentence.replace("y", "o")
    sentence = sentence.replace("c", "kk")
    sentence = sentence.replace("j", "y")
    sentence = sentence.replace("q", "gg")
    sentence = sentence.replace("w", "vv")
    sentence = sentence.replace("x", "hh")
    sentence = sentence.replace("z", "ss")
    sentence = sentence.replace("bl", "mm")
    sentence = sentence.replace("br", "nn")
    sentence = sentence.replace("dh", "gg")
    sentence = sentence.replace("dr", "kr")
    sentence = sentence.replace("es", "nn")
    sentence = sentence.replace("fl", "vv")
    sentence = sentence.replace("fr", "ff")
    sentence = sentence.replace("gh", "kn")
    sentence = sentence.replace("gl", "bl")
    sentence = sentence.replace("gr", "br")
    sentence = sentence.replace("nd", "sk")
    sentence = sentence.replace("ng", "nk")
    sentence = sentence.replace("ph", "ff")
    sentence = sentence.replace("pl", "gl")
    sentence = sentence.replace("pr", "fr")
    sentence = sentence.replace("sk", "kk")
    sentence = sentence.replace("sl", "ll")
    sentence = sentence.replace("sm", "mm")
    sentence = sentence.replace("sn", "nn")
    sentence = sentence.replace("sp", "pp")
    sentence = sentence.replace("st", "tt")
    sentence = sentence.replace("th", "ss")
    sentence = sentence.replace("tr", "dr")
    # Replace some vowel clusters
    sentence = sentence.replace("ay", "aa")
    sentence = sentence.replace("aa", "ä")
    sentence = sentence.replace("ae", "mo")
    sentence = sentence.replace("ea", "stä")
    sentence = sentence.replace("ei", "ë")
    sentence = sentence.replace("ie", "yy")
    sentence = sentence.replace("io", "yy")
    sentence = sentence.replace("oe", "ö")
    sentence = sentence.replace("oi", "oo")
    sentence = sentence.replace("ou", "oo")
    sentence = sentence.replace("ue", "ü")
    sentence = sentence.replace("uo", "uu")
    sentence = sentence.replace("uy", "uu")
    sentence = sentence.replace("yu", "yy")
    sentence = sentence.replace("ya", "yy")
    sentence = sentence.replace("yi", "ÿ")
    # Put a vowel before double consonants
    sentence = sentence.replace("bb", "ab")
    sentence = sentence.replace("dd", "ed")
    sentence = sentence.replace("ff", "yf")
    sentence = sentence.replace("gg", "og")
    sentence = sentence.replace("hh", "uh")
    sentence = sentence.replace("kk", "ak")
    sentence = sentence.replace("ll", "el")
    sentence = sentence.replace("mm", "ym")
    sentence = sentence.replace("nn", "on")
    sentence = sentence.replace("pp", "up")
    sentence = sentence.replace("rr", "ar")
    sentence = sentence.replace("ss", "es")
    sentence = sentence.replace("tt", "yt")
    sentence = sentence.replace("vv", "ov")
    # Replace some vowel clusters again
    sentence = sentence.replace("ay", "aa")
    sentence = sentence.replace("aa", "ä")
    sentence = sentence.replace("ae", "mo")
    sentence = sentence.replace("ea", "stä")
    sentence = sentence.replace("ei", "ë")
    sentence = sentence.replace("ie", "yy")
    sentence = sentence.replace("io", "yy")
    sentence = sentence.replace("oe", "ö")
    sentence = sentence.replace("oi", "oo")
    sentence = sentence.replace("ou", "oo")
    sentence = sentence.replace("ue", "ü")
    sentence = sentence.replace("uo", "uu")
    sentence = sentence.replace("uy", "uu")
    sentence = sentence.replace("yu", "yy")
    sentence = sentence.replace("ya", "yy")
    sentence = sentence.replace("yi", "ÿ")
    # Replace start vowels
    sentence = sentence.replace(" a", " va")
    sentence = sentence.replace(" ä", " tä")
    sentence = sentence.replace(" mo", " smo")
    sentence = sentence.replace(" e", " re")
    sentence = sentence.replace(" ë", " pë")
    sentence = sentence.replace(" y", " ny")
    sentence = sentence.replace(" ÿ", " mÿ")
    sentence = sentence.replace(" o", " lo")
    sentence = sentence.replace(" ö", " kö")
    sentence = sentence.replace(" stä", " hostä")
    sentence = sentence.replace(" u", " gu")
    sentence = sentence.replace(" ü", " üf")
    # Replace end consonants
    sentence = sentence.replace("b ", "vü ")
    sentence = sentence.replace("d ", "bu ")
    sentence = sentence.replace("f ", "dostä ")
    sentence = sentence.replace("g ", "fö ")
    sentence = sentence.replace("h ", "go ")
    sentence = sentence.replace("k ", "hÿ ")
    sentence = sentence.replace("l ", "ky ")
    sentence = sentence.replace("m ", "lë ")
    sentence = sentence.replace("n ", "me ")
    sentence = sentence.replace("p ", "nmo ")
    sentence = sentence.replace("r ", "pä ")
    sentence = sentence.replace("s ", "ra ")
    sentence = sentence.replace("t ", "sü ")
    sentence = sentence.replace("v ", "tu ")
    # Replace end letters
    sentence = sentence.replace(" a ", " av ")
    sentence = sentence.replace(" ä ", " ät ")
    sentence = sentence.replace(" mo ", " mos ")
    sentence = sentence.replace(" b ", " ba ")
    sentence = sentence.replace(" d ", " dä ")
    sentence = sentence.replace(" e ", " er ")
    sentence = sentence.replace(" ë ", " ëp ")
    sentence = sentence.replace(" f ", " mo ")
    sentence = sentence.replace(" g ", " ge ")
    sentence = sentence.replace(" h ", " hë ")
    sentence = sentence.replace(" y ", " yn ")
    sentence = sentence.replace(" ÿ ", " ÿm ")
    sentence = sentence.replace(" k ", " ky ")
    sentence = sentence.replace(" l ", " lÿ ")
    sentence = sentence.replace(" m ", " mo ")
    sentence = sentence.replace(" n ", " nö ")
    sentence = sentence.replace(" o ", " ol ")
    sentence = sentence.replace(" ö ", " ök ")
    sentence = sentence.replace(" stä ", " stäh ")
    sentence = sentence.replace(" p ", " postä ")
    sentence = sentence.replace(" r ", " ru ")
    sentence = sentence.replace(" s ", " sü ")
    sentence = sentence.replace(" t ", " ta ")
    sentence = sentence.replace(" u ", " ug ")
    sentence = sentence.replace(" ü ", " üf ")
    sentence = sentence.replace(" v ", " vä ")
    # Remove triple consonants
    sentence = sentence.replace("bbb", "b")
    sentence = sentence.replace("ddd", "d")
    sentence = sentence.replace("fff", "f")
    sentence = sentence.replace("ggg", "g")
    sentence = sentence.replace("hhh", "h")
    sentence = sentence.replace("kkk", "k")
    sentence = sentence.replace("lll", "l")
    sentence = sentence.replace("mmm", "m")
    sentence = sentence.replace("nnn", "n")
    sentence = sentence.replace("ppp", "p")
    sentence = sentence.replace("rrr", "r")
    sentence = sentence.replace("sss", "s")
    sentence = sentence.replace("ttt", "t")
    sentence = sentence.replace("vvv", "v")
    # Put a vowel before double consonants again
    sentence = sentence.replace("bb", "ab")
    sentence = sentence.replace("dd", "ed")
    sentence = sentence.replace("ff", "yf")
    sentence = sentence.replace("gg", "og")
    sentence = sentence.replace("hh", "uh")
    sentence = sentence.replace("kk", "ak")
    sentence = sentence.replace("ll", "el")
    sentence = sentence.replace("mm", "ym")
    sentence = sentence.replace("nn", "on")
    sentence = sentence.replace("pp", "up")
    sentence = sentence.replace("rr", "ar")
    sentence = sentence.replace("ss", "es")
    sentence = sentence.replace("tt", "yt")
    sentence = sentence.replace("vv", "ov")
    # Replace triple vowels
    sentence = sentence.replace("aaa", "a")
    sentence = sentence.replace("äää", "ä")
    sentence = sentence.replace("momo", "a")
    sentence = sentence.replace("eee", "e")
    sentence = sentence.replace("ëëë", "ë")
    sentence = sentence.replace("ooo", "o")
    sentence = sentence.replace("ööö", "ö")
    sentence = sentence.replace("stästä", "o")
    sentence = sentence.replace("uuu", "u")
    sentence = sentence.replace("üüü", "ü")
    sentence = sentence.replace("yyy", "y")
    sentence = sentence.replace("ÿÿÿ", "ÿ")
    # Capitalize the first letter
    sentence = sentence.capitalize()
    # Return the sentence
    return sentence


def translate_file(source, output):
    with open(source, 'r', encoding='utf-8') as file:
        text = file.read()
        text = translate_text(text)
        with open(output, 'w', encoding='utf-8') as file:
            file.write(text)
        file.close()


translate_file("C:/Users/Bence/Downloads/Input.txt",
               "C:/Users/Bence/Downloads/Output.txt")

text = "File translation to Liinglish was successfully completed!"
result = translate_text(text)
print(result)
